from typing import Dict, Any, List, Optional
import uuid
from pydantic import BaseModel, Field
from src.agents.state import InterviewState, QuestionPlan
from src.agents.prompts.registry import PromptRegistry
from src.services.llm import ILLMClient, get_llm_client


class PlannedQuestion(BaseModel):
    """
    Sub-schema for individual questions generated by the LLM Planner.
    """
    topic: str = Field(..., description="The technical skill or experience dimension to evaluate")
    question_text: str = Field(..., description="The interview question content")
    expected_keywords: List[str] = Field(..., description="Expected key terms to listen for in candidate responses")


class InterviewPlanResponse(BaseModel):
    """
    Schema for generating structured interview plans with the LLM wrapper.
    """
    questions: List[PlannedQuestion] = Field(..., description="Sequential list of interview questions")


class PlannerNode:
    """
    LangGraph action node responsible for generating a customized evaluation plan
    based on the resume and job description.
    """
    def __init__(self, llm_client: Optional[ILLMClient] = None) -> None:
        self.llm_client = llm_client

    def _get_client(self) -> ILLMClient:
        return self.llm_client or get_llm_client("planner")

    def _generate_dynamic_questions(self, job_title: str, parsed_jd: Dict[str, Any], parsed_resume: Dict[str, Any]) -> List[PlannedQuestion]:
        """
        Dynamically derives tailored interview questions based specifically on the candidate's projects,
        their experience level, skills specified in the resume, and JD technical requirements.
        """
        def _get_dict(obj):
            if isinstance(obj, dict):
                if isinstance(obj.get("parsed_attributes"), dict):
                    return obj["parsed_attributes"]
                return obj
            return {}

        jd_attr = _get_dict(parsed_jd)
        resume_attr = _get_dict(parsed_resume)

        tech_stack = jd_attr.get("tech_stack", []) or []
        min_exp = jd_attr.get("minimum_experience_years", 0.0) or 0.0

        resume_skills = resume_attr.get("skills", []) or []
        projects = resume_attr.get("projects", []) or []
        past_roles = resume_attr.get("past_roles", []) or []
        cand_exp = resume_attr.get("experience_years", 0.0) or 0.0

        # Combine skills uniquely
        all_skills = list(dict.fromkeys(tech_stack + resume_skills))
        primary_tech = all_skills[0] if all_skills else "Backend Architecture"
        secondary_tech = all_skills[1] if len(all_skills) > 1 else "API Engineering"
        database_tech = next((s for s in all_skills if any(db in s.lower() for db in ["sql", "postgres", "mysql", "mongo", "db"])), "Database Systems")

        # Extract project reference or role reference
        project_name = projects[0] if projects else (past_roles[0] if past_roles else f"{primary_tech} System Project")
        secondary_project = projects[1] if len(projects) > 1 else f"production {secondary_tech} implementation"

        exp_label = f"{cand_exp:g}" if cand_exp > 0 else "3+"

        return [
            PlannedQuestion(
                topic=f"Project Deep Dive - {project_name}",
                question_text=f"In your resume, you highlighted your work on {project_name}. Could you walk me through the system architecture, technical choices, and your direct role in delivering this project for the {job_title} role?",
                expected_keywords=[project_name.lower(), "architecture", "contribution", "design", "deliverable"]
            ),
            PlannedQuestion(
                topic=f"Project Engineering & {primary_tech}",
                question_text=f"When engineering {project_name}, what were the biggest technical bottlenecks or design trade-offs you encountered, and how did you resolve them using {primary_tech}?",
                expected_keywords=[primary_tech.lower(), "bottleneck", "tradeoff", "optimization", "resolution"]
            ),
            PlannedQuestion(
                topic=f"Role & Experience Alignment ({exp_label} YOE)",
                question_text=f"With your {exp_label} years of experience applying for this {job_title} position, how have you utilized {secondary_tech} to meet production scalability and reliability requirements?",
                expected_keywords=[secondary_tech.lower(), "scalability", "reliability", "production", "experience"]
            ),
            PlannedQuestion(
                topic=f"Data Persistence & {database_tech}",
                question_text=f"Describe your approach to database schema design, query optimization, and storage management using {database_tech} across your past projects.",
                expected_keywords=[database_tech.lower(), "schema", "indexing", "query", "optimization"]
            ),
            PlannedQuestion(
                topic="System Reliability & Deployment Pipeline",
                question_text=f"Walk me through your end-to-end testing strategy, peer code review process, and CI/CD deployment pipeline when shipping critical features for the {job_title} role.",
                expected_keywords=["testing", "ci/cd", "deployment", "code review", "quality"]
            )
        ]

    async def execute(self, state: InterviewState) -> Dict[str, Any]:
        """
        Executes LLM planning to evaluate resume-JD mismatch details and append
        a queue of 5 structured questions into the conversation state.
        """
        parsed_jd = state.get("parsed_jd", {})
        parsed_resume = state.get("parsed_resume", {})
        job_title = state.get("job_title", "Target Role")

        # Compile prompts
        user_prompt = PromptRegistry.compile_user_prompt(
            prompt_key="planner",
            job_title=job_title,
            jd_attributes=str(parsed_jd.get("parsed_attributes", parsed_jd)),
            resume_attributes=str(parsed_resume.get("parsed_attributes", parsed_resume)),
            num_questions=5
        )
        system_instruction = PromptRegistry.get_system_prompt("planner")

        raw_questions: List[PlannedQuestion] = []
        try:
            import asyncio
            plan_response = await asyncio.wait_for(
                self._get_client().generate_structured_json(
                    prompt=user_prompt,
                    response_schema=InterviewPlanResponse,
                    system_instruction=system_instruction
                ),
                timeout=25.0
            )
            raw_questions = plan_response.questions
        except Exception:
            raw_questions = []

        # If LLM returned generic fallback or empty plan, derive 5 dynamic questions from JD & Resume
        if not raw_questions or (len(raw_questions) > 0 and raw_questions[0].question_text == "What is a decorator?"):
            raw_questions = self._generate_dynamic_questions(job_title, parsed_jd, parsed_resume)

        questions_plan: List[QuestionPlan] = []
        for q in raw_questions:
            questions_plan.append({
                "id": str(uuid.uuid4()),
                "topic": q.topic,
                "question_text": q.question_text,
                "expected_keywords": q.expected_keywords,
                "status": "pending"
            })

        return {
            "questions_plan": questions_plan,
            "current_question_index": 0,
            "is_completed": False
        }
