apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: interview-agent

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml

images:
  - name: interviewagentacr2026hmk.azurecr.io/interview-agent-backend
    newTag: latest
  - name: interviewagentacr2026hmk.azurecr.io/interview-agent-frontend
    newTag: latest
